# Generated by Django 5.1.3 on 2025-05-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sub',
            field=models.CharField(blank=True, help_text='Subject identifier from JWT token or OAuth provider', max_length=255, null=True, verbose_name='Subject Identifier'),
        ),
    ]
